### ISSUE TITLE
bcc does not work

### ISSUE THREAD

**Issue by btknorr** [nodemailer/mailcomposer#65]
mailcomposer uses buildmail which by default excludes bcc unless you tell it to keepBcc.  Why is this not turned on for mailcomposer?

**Comment by andris9** [comment]
If you keep BCC header in the message then everybody will see who the BCC recipients are since this header is not removed by anyone by default.

**Comment by btknorr** [comment]
So why does the documentation state we can send emails via bcc?  But they are never sent.

**Comment by andris9** [comment]
Bcc is included in the message source when you need to transmit the message without using SMTP. Eg. when piping the message to `sendmail`. Otherwise the bcc addresses are stored and used in the SMTP envelope but not included in the rfc822 message source. If you really want to keep the Bcc header you can do it like this:

```javascript
var mail = mailcomposer(data);
mail.keepBcc = true;
```
