### ISSUE TITLE
PDF attachments corrupted when running on Heroku

### ISSUE THREAD

**Issue by realyze** [nodemailer/mailcomposer#74]
My app runs on Heroku and I'm using `mail.createReadStream()` and `request` (it's meteor package https://github.com/froatsnook/meteor-request) to stream emails to Gmail API.

This is the code that sends the message:

```
const response = request.postSync('https://www.googleapis.com/upload/gmail/v1/users/me/messages/send?uploadType=media', {
  headers: _.extend({}, headers, {'Content-Type': 'message/rfc822'}),
  body: mail.createReadStream()
});
```

Gmail returns HTTP 200 but the uploaded PDF almost always gets corrupted (and it's size is smaller than it should be). Images seem to get through fine, only PDFs get broken.

The funny thing is that I can't reproduce the corruption on localhost, just Heroku.

And last bit - if I use `mail.build` and upload a string instead of streaming the payload, it works fine (PDF have right size).

**Comment by realyze** [comment]
BTW, I always feel bad when filing bugs with opensource libraries so to make up for that at least a little bit: I love mailcomposer - thanks for all the hard work!

**Comment by andris9** [comment]
Try to upload the same file by stream and as string, then download the resulting emails from Gmail (in Gmail look for Show original) and diff these to see where's the difference.

**Comment by realyze** [comment]
Hmm, the relevant part of the messages looks like this:
```
--001a114d71709f60de053f523f7d--
--001a114d71709f60e4053f523f7f
Content-Type: application/pdf; name="Starter Kit Book Report Outline 2012.pdf"
Content-Disposition: attachment; filename="Starter Kit Book Report Outline 2012.pdf"
Content-Transfer-Encoding: base64
X-Attachment-Id: a8ef40d16031fbe8_0.1


--001a114d71709f60e4053f523f7f--
```

The boundary markers and the `X-Attachment-Id` are different but that's expected.

It almost looks like as if the attachment stream got terminated early for some reason but didn't report an error? FWIW, the attachments are stored on FileStack (they used to be called FilePicker).

I wonder why if the difference could be that I'm running it locally on a Mac whereas Heroku is Linux... (sadly, I don't have a linux VM to play with at this time and most probably won't find time to look into this this week).

**Comment by realyze** [comment]
BTW here's a link to the broken truncated PDF file (if that helps at all).

[sp_broken_pdf.pdf](https://github.com/nodemailer/mailcomposer/files/543483/sp_broken_pdf.pdf)

**Comment by andris9** [comment]
Gmail seems to be rewriting the message as boundaries do not look like the ones generated by mailcomposer, so not much help from there. What happens if you add multiple attachments? Do all attachments end up corrupted? One difference between uploading streams and strings is that in the latter case the request module knows the length of the data and so it can provide the Content-Length header. If the length is not known beforehand then the upload is done using chunked encoding, maybe the transport layer fails somehow?

The problem might be related by fetching PDF stream – if you are uploading the message in the same time then this also caps the speed for fetching PDF. Or it might be related to uploading which might be related to the transport encoding and not knowing content-length. If you have an actual error somewhere then mailcomposer should return it.

Anyway, as I can't reproduce it myself then I'm not able to debug this problem or find out what is going on.
