### ISSUE TITLE
Parenthesis in attachment filename

### ISSUE THREAD

**Issue by Stephen-Meyerhofer** [nodemailer/mailcomposer#78]
I am using mailcomposer to make an email Buffer object with MIME and then sending the message with AWS SES sendRawEmail API. The following, I think, is inconsistent behavior.

Works fine:
```
Content-Type: application/pdf; name=(E)E.pdf
Content-Disposition: attachment; filename="(E)E.pdf"
```

Works fine:
```
Content-Type: application/pdf; name=().pdf
Content-Disposition: attachment; filename="().pdf"
```

This one says "expected ; before E.pdf":
```
Content-Type: application/pdf; name=E(E)E.pdf
Content-Disposition: attachment; filename="E(E)E.pdf"
```

This one complains about unbalanced parenthesis:
```
Content-Type: application/pdf; name=E(E.pdf
Content-Disposition: attachment; filename="E(E.pdf"
```

Why is the quoting behavior inconsistent between the Content-Type's name and the Content-Disposition's filename?

**Comment by andris9** [comment]
This was a bug. Header param values, if unquoted, can only include latin characters, numbers and some special characters but not "(" or ")". You can find the actual syntax [here](https://tools.ietf.org/html/rfc2045#section-5.1) (see definitions for "value:=").

"filename" in "Content-Disposition" was handled already correctly. The "name" parameter in "Content-Type" is not even standard, it only exists here to support some legacy and invalidly behaving mail clients (like QQ webmail), so in normal conditions it should not matter if the filename in "Content-Type" is properly formatted or not and I guess that's why it went unnoticed so far.

**Comment by andris9** [comment]
Btw the error about unbalanced parenthesis that you got is about the fact that using parenthesis in non-quoted text can be actually used but it's with a twist - anything between "(" and ")" is a comment and it gets removed by the recipient mail client.

**Comment by Stephen-Meyerhofer** [comment]
Thanks for publishing a fix so quickly. It would have taken me much longer to find out that the source of the bug existed in the buildmail project.

The fact that you support mail clients I haven't even heard of gives me greater confidence that this project generates a good MIME message.
